### ISSUE TITLE
TODO: GregTech compat

### ISSUE THREAD

**Issue by 3TUSK** [FrogCraft-Rebirth/FrogCraft-Rebirth#8]
~~As title shown. The major question is that, GT5 and GT6 are totally different from each other. Thus, there are two options:~~
- ~~Separate into different `compat` module~~
- ~~Make something universal~~

~~Also,~~ here is a list of (GT) compat module content ~~(unfinished)~~:
- [ ] OreDictionary registry. I think it can be automatically handled by GregTech itself...
- [ ] Pneumatic Compressor: alternative of Implosive Compressor, no industrial TNT is required, less noise (maybe), and high price!
- [ ] Mobile power supply: solar generator cover, all kinds of upgrades, etc.

**Comment by 3TUSK** [comment]
Drop off TechReborn compat _temporarily_, cause I am lazy right now.
